[package]
name = "parcheck"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
fastrand = { version = "2.1", optional = true }
futures-util = { version = "0.3", optional = true }
tokio = { version = "1", features = ["sync", "rt"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
enable = ["dep:fastrand", "dep:tokio", "dep:futures-util"]